### ISSUE TITLE
Python 3.9+ support

### ISSUE THREAD

**Issue by kocunop** [Mactory/django-pluggableappsettings#3]
`AttributeError: module 'collections' has no attribute 'Iterable'`

Python docs:

Deprecated since version 3.3, will be removed in version 3.9: Moved Collections Abstract Base Classes to the collections.abc module. For backwards compatibility, they continue to be visible in this module through Python 3.8.

**Comment by Mactory** [comment]
Thank you for your MR. I just merged it in 👍

**Comment by kocunop** [comment]
Good news! 
I go to update my project =)
